### ISSUE TITLE
Add a contributors section to the Home Page of website

### ISSUE THREAD

**Issue by fykaa** [fykaa/techOS-Bell#12]
Link  -> https://github.com/fykaa/techOS-Bell/graphs/contributors to the homepage such that it presents the Contributors directly in the footer section of the Home Page

![image](https://user-images.githubusercontent.com/97490463/194953059-0765431e-a4dd-4561-90f3-09910d1b7410.png)

Rules - 

1) Comment below to Get Assigned
2) The PR Should be sent within 48 hours of Assignment, else will get reassigned to the next person.
3) The PR should be valid and have no Merge Conflicts
4) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format
5) Must Follow all the steps from [Instructions](https://github.com/fykaa/techOS-Bell/blob/main/README.md#instructions-for-successfully-merged-pr-under-hacktoberfest-)

**Comment by jsvigneshkanna** [comment]
Assign me this issue, will work on it
