### ISSUE TITLE
About Us section text is not visible.

### ISSUE THREAD

**Issue by Adityageek** [fykaa/techOS-Bell#22]
About Us section text is not visible. Please refer the screenshot below.
![image](https://user-images.githubusercontent.com/33696459/196268073-c38b629e-f51c-4140-b2e0-308e4b727ae3.png)

**Comment by Adityageek** [comment]
Hi @fykaa Can I pick this issue? Thanks!

**Comment by fykaa** [comment]
Assigned, also lookk forward for the text in the contributors section
