### ISSUE TITLE
Add a suitable FAQs section to the Website

### ISSUE THREAD

**Issue by fykaa** [fykaa/techOS-Bell#24]
Add a new FAQ section to the Website just above Contributor's section
![image](https://user-images.githubusercontent.com/97490463/196508622-737970f2-c5e0-4eee-b834-2b6b14b07379.png)

Take Reference from -
https://codyhouse.co/gem/css-faq-template
https://bootsnipp.com/snippets/z8e5d

Example - 
![image](https://user-images.githubusercontent.com/97490463/196508465-a28b3201-53fa-4f2b-85af-c4771f288653.png)

Must Have in PR - 
- Add proper styling and Wrapping effect using JavaScript
- The color and design should match the website theme
- Smooth gliding is preferred

Rules -
1) Must Follow all the steps from [Instructions](https://github.com/fykaa/techOS-Bell#instructions-for-successfully-merged-pr-under-hacktoberfest-)
2) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.
3) The PR should be valid and have no Merge Conflicts
4) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format

**Comment by fykaa** [comment]
Assigned.

**Comment by fykaa** [comment]
@BGS89 You can add  5 random community questions, our team will be updating the data

**Comment by BGS89** [comment]
Hi @fykaa I have submitted a PR for review : )
