### ISSUE TITLE
The headline text on the footer is not visible

### ISSUE THREAD

**Issue by LeGrandMAG** [fykaa/techOS-Bell#26]
I just noticed that the headline text of the footer has a dark text color (similar to the background), which makes it invisible.

Below are screenshots of the footer.

<div>
<img height="200" src="https://user-images.githubusercontent.com/64711820/196723665-2d7032f5-8bd8-4f1e-add7-ca33677d6030.png">
<p><em>Footer when I do not underline the headline</em></p>
</div>
<div>
<img  height="200" src="https://user-images.githubusercontent.com/64711820/196723688-70d87845-4ea5-4e34-8f79-84e9ca761abd.png">
<p><em>Footer when underline the headline</em></p>
</div>

I would be glad to work on this issue

**Comment by fykaa** [comment]
You're assigned, also look forward to the following

Must have in the PR - 
1) Fixed About section color mismatch
2) Contributors section made responsive and fixing color mismatch

Rules -
1) Must Follow all the steps from [Instructions](https://github.com/fykaa/techOS-Bell#instructions-for-successfully-merged-pr-under-hacktoberfest-)
2) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.
3) The PR should be valid and have no Merge Conflicts
4) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format

**Comment by LeGrandMAG** [comment]
Okay, I will work on this issue and get back to you as soon as possible.

**Comment by fykaa** [comment]
Fixed
