### ISSUE TITLE
Misleading links on the footer

### ISSUE THREAD

**Issue by LeGrandMAG** [fykaa/techOS-Bell#27]
I have noticed that the link on the footer are misleading.

1. The "OpenSource ❤" link is invalid.
2.  The LinkedIn: doesn't lead anywhere.
3. The github: doesn't lead anywhere.
4. The instagram: doesn't lead anywhere and the text that display when I hover over the icon says "youtube" instead of instagram.
5. Individual picture of the contributors all lead to the same page. It is better to either to put the alltogether in a same image, or put individual link the their personal profile.

I would be glad to work on this issue.

**Comment by fykaa** [comment]
Hey, this enhancement will be looked forward by the team. Thanks for your concern.
