### ISSUE TITLE
Add a floating Scroll-to-Top Button on the right side

### ISSUE THREAD

**Issue by fykaa** [fykaa/techOS-Bell#32]
![image](https://user-images.githubusercontent.com/97490463/196951196-a958c5f9-1dcf-4a5e-9b64-d9188ffcd621.png)

Must have in the PR - 
1) Responsive Scroll-to-Top button
2) Suitable and Professional Design
3) Smooth scrolling to the top

Take reference from -
https://www.freecodecamp.org/news/back-to-top-button-and-page-progressbar-with-html-css-and-js/
https://css-tricks.com/how-to-make-an-unobtrusive-scroll-to-top-button/

Rules -
1) Must Follow all the steps from [Instructions](https://github.com/fykaa/techOS-Bell#instructions-for-successfully-merged-pr-under-hacktoberfest-)
2) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.
3) The PR should be valid and have no Merge Conflicts
4) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format

**Comment by BGS89** [comment]
@fykaa I would like to do this. Please assign me : )
