### ISSUE TITLE
Make the COntributor's section Responsive

### ISSUE THREAD

**Issue by fykaa** [fykaa/techOS-Bell#33]
![image](https://user-images.githubusercontent.com/97490463/196954529-5b9fdbdf-125d-41be-87dc-bafcd0e1f4da.png)

Must have in the PR - 
1) Fix the Contributor's Heading Font Color
2) Make the Contributor's image Responsive

Rules -

1) Must Follow all the steps from [Instructions](https://github.com/fykaa/techOS-Bell#instructions-for-successfully-merged-pr-under-hacktoberfest-)
2) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.
3) The PR should be valid and have no Merge Conflicts
4) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format

**Comment by azeddine011** [comment]
Hi @fykaa, could u please assign this to me;

**Comment by fykaa** [comment]
@azeddine011 Assigned
