### ISSUE TITLE
Text in the About Us section is not visible

### ISSUE THREAD

**Issue by LeGrandMAG** [fykaa/techOS-Bell#35]
The text in the about section is not visible enough.

Here is how it is displayed

![image](https://user-images.githubusercontent.com/64711820/196963609-6640d4fa-3388-438e-b009-36854d76b9df.png)

I would be glad to fix this issue

**Comment by DeveVivek** [comment]
Please assign me this issue.

**Comment by fykaa** [comment]
Fixed in another Major PR :)
