### ISSUE TITLE
Add Creative Navbar design

### ISSUE THREAD

**Issue by fykaa** [fykaa/techOS-Bell#4]
Update the Navbar UI -
![image](https://user-images.githubusercontent.com/97490463/194856179-9d9135e8-c1fe-4b15-adab-ff58013309da.png)

Take help from - https://themewagon.com/responsive-navbar-collection/

Must have in the PR - 
1) Proper creative Hover effect
2) Responsive (add a Hamburger Menu for Mobile devices)
3) Smooth scrolling and attractive design

Rules -
1) Comment below to Get Assigned
2) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.
3) The PR should be valid and have no Merge Conflicts
4) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format

**Comment by jsvigneshkanna** [comment]
Please assign me this issue, will raise a PR in some time

**Comment by Eddayavuz** [comment]
Can I work on this as well?
