### ISSUE TITLE
Add a Testimonials Section with Attractive UI and Effects

### ISSUE THREAD

**Issue by fykaa** [fykaa/techOS-Bell#5]
Add a Testimonials Section to the Homepage below the about us section-
![image](https://user-images.githubusercontent.com/97490463/194861281-2c6cbd3b-26b8-4836-b519-23c88e772b0d.png)

Samples - 
![image](https://user-images.githubusercontent.com/97490463/194861431-f857f79b-3e8f-4f47-a8c1-ee5f639a9c72.png)
![image](https://user-images.githubusercontent.com/97490463/194861440-0d7dae56-8ca6-4c6d-9bd8-20b7c3301d8a.png)
![image](https://user-images.githubusercontent.com/97490463/194861446-8165d330-bbb1-4451-8fe7-5f01938b5fcc.png)

----
Must have in the PR - 
1) Proper creative Hover effect to each Testimonial 
2) Responsive (add a Hamburger Menu for Mobile devices)
3) Smooth scrolling and attractive design
4) The testimonials should occupy a specific length and have a left-right scrolling effect for each

Rules -
1) Comment below to Get Assigned
2) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.
3) The PR should be valid and have no Merge Conflicts
4) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format

**Comment by ThPadelis** [comment]
Hello, I would like to help with this one

**Comment by fykaa** [comment]
@ThPadelis Sure :) 
I've assigned you this issue.
